test_name: "simple test"
vars:
  Url: https://httpbin.org  # This will NOT be overwritten by vars.yaml
  Tracer: abc1234
  Import: test_scripts/includes/vars.yaml  # Import some vars from an external file - see test_scripts/vars.yaml for format
imports:
  PostJsonData: test_scripts/includes/post_json_data.yaml
  PostFormData: test_scripts/includes/post_form_data.yaml
stages:
  -
    import: PostJsonData
  -
    import: PostFormData
  - name: httpbin.org
    before: |+
      environment["X-Test-Header"] = "TestHeader";
      console.log(JSON.stringify(environment, null, 4));
    request:
      method: GET
      url: "{{.Url}}"
      url_pattern: "get"
      headers:
        X-Tracer_Id: "{{.Tracer}}"
    response:
      status_code: 200
      resp_values:
        json:
          Origin: origin
      expectations:
        - type: status
          arguments:
            - 200
    after: |+
      console.log(JSON.stringify(environment, null, 4));
