test_name: "tavern test server tests"
vars:
  Url: http://localhost:5000
stages:
  -
    name: public page access
    request:
      method: GET
      url: "{{.Url}}"
      url_pattern: ""
    response:
      status_code:
        - 200
      actions:
        - type: print_response
  -
    name: Get a number not logged in yet
    request:
      method: GET
      url: "{{.Url}}"
      url_pattern: "numbers"
    headers:
      Content-Type: "application/json"
    response:
      status_code:
        - 400
      actions:
        - type: print_response
  -
    name: login
    request:
      method: POST
      url: "{{.Url}}"
      url_pattern: "login"
      headers:
        Content-Type: "application/x-www-form-urlencoded"
      data:
        username: "jon"
        password: "shhh!"
    response:
      status_code:
        - 200
      resp_values:
        json:
          Token: token
      actions:
        - type: print_response
  -
    name: Get a number that is not in the DB
    request:
      method: GET
      url: "{{.Url}}"
      url_pattern: "numbers"
      headers:
        Authorization: Bearer {{.Token}}
        Content-Type: "application/json"
      json:
        name: test1
    response:
      status_code:
        - 404
      actions:
        - type: print_response
  -
    name: Add a number to the list
    request:
      method: POST
      url: "{{.Url}}"
      url_pattern: "numbers"
      headers:
        Authorization: Bearer {{.Token}}
        Content-Type: "application/json"
      json:
        name: test1
        number: 23
    response:
      status_code:
        - 201
      actions:
        - type: print_response
  -
    name: Get a number OK
    request:
      method: GET
      url: "{{.Url}}"
      url_pattern: "numbers"
      headers:
        Authorization: Bearer {{.Token}}
        Content-Type: "application/json"
      json:
        name: test1
    response:
      status_code:
        - 200
      actions:
        - type: print_response